In [30]:
import pandas as pd

import numpy as np

In [31]:
data = pd.read_csv('./TIA-WEATHER-DATA-2015-01-01-TO-2025-06-30.csv')
data.columns

Index(['datetime', 'tempmax', 'tempmin', 'temp', 'dew', 'humidity',
       'precipprob', 'precipcover', 'preciptype', 'windgust', 'windspeed',
       'winddir', 'sealevelpressure', 'cloudcover', 'visibility',
       'solarradiation', 'solarenergy', 'uvindex', 'severerisk', 'sunrise',
       'sunset', 'precipitation'],
      dtype='str')

In [32]:
data[0:50]

,datetime,tempmax,tempmin,temp,dew,humidity,precipprob,precipcover,preciptype,windgust,...,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,sunrise,sunset,precipitation
0,2015-01-01,60.7,39.1,50.0,41.7,74.7,100,4.17,rain,11.2,...,1020.4,79.1,2.4,96.6,8.3,4,NaN,2015-01-01T06:54:15,2015-01-01T17:19:31,0.8
1,2015-01-02,71.0,49.9,54.9,48.4,80.1,100,20.83,rain,19.9,...,1022.2,93.3,2.9,40.4,3.3,2,NaN,2015-01-02T06:54:31,2015-01-02T17:20:12,0.0
2,2015-01-03,67.7,48.1,54.8,50.5,86.3,100,8.33,rain,15.4,...,1021.0,90.3,2.8,58.6,5.0,4,NaN,2015-01-03T06:54:46,2015-01-03T17:20:54,0.5
3,2015-01-04,69.9,48.1,54.5,49.6,85.5,100,4.17,rain,17.0,...,1018.1,67.1,2.7,118.0,10.3,6,NaN,2015-01-04T06:54:58,2015-01-04T17:21:37,0.5
4,2015-01-05,64.3,42.7,51.3,45.7,83.2,0,0.00,NaN,16.3,...,1013.9,41.6,3.9,139.2,12.0,6,NaN,2015-01-05T06:55:10,2015-01-05T17:22:20,0.0
5,2015-01-06,62.5,46.3,52.2,45.0,78.0,0,0.00,NaN,16.1,...,1016.4,62.5,3.7,98.8,8.5,5,NaN,2015-01-06T06:55:20,2015-01-06T17:23:04,0.0
6,2015-01-07,60.7,43.4,50.3,43.1,77.8,0,0.00,NaN,15.7,...,1017.1,65.7,3.4,102.8,8.9,5,NaN,2015-01-07T06:55:28,2015-01-07T17:23:49,0.0
7,2015-01-08,71.7,39.1,49.3,41.5,76.4,100,4.17,rain,15.7,...,1018.9,50.1,3.9,114.1,9.7,5,NaN,2015-01-08T06:55:35,2015-01-08T17:24:34,0.0
8,2015-01-09,64.3,39.1,48.4,38.7,72.8,0,0.00,NaN,15.4,...,1020.3,24.0,3.8,173.6,14.8,7,NaN,2015-01-09T06:55:40,2015-01-09T17:25:20,0.0
9,2015-01-10,67.9,35.5,47.9,35.7,68.2,0,0.00,NaN,12.1,...,1018.8,22.9,3.9,190.1,16.2,7,NaN,2015-01-10T06:55:44,2015-01-10T17:26:06,0.0
10,2015-01-11,66.1,37.3,49.3,36.3,64.8,0,0.00,NaN,11.6,...,1019.3,52.2,3.7,185.8,15.9,7,NaN,2015-01-11T06:55:46,2015-01-11T17:26:52,0.0
11,2015-01-12,66.1,37.3,49.1,38.4,71.1,0,0.00,NaN,13.2,...,1020.7,31.3,3.3,188.1,16.2,7,NaN,2015-01-12T06:55:47,2015-01-12T17:27:39,0.0
12,2015-01-13,66.1,37.3,49.7,39.6,72.0,100,4.17,rain,14.5,...,1020.3,27.0,3.4,191.5,16.5,7,NaN,2015-01-13T06:55:46,2015-01-13T17:28:27,0.0
13,2015-01-14,66.1,37.3,49.4,38.3,70.5,0,0.00,NaN,13.9,...,1021.1,25.0,3.5,187.5,16.0,7,NaN,2015-01-14T06:55:43,2015-01-14T17:29:15,0.0
14,2015-01-15,75.8,37.3,50.0,39.2,70.3,0,0.00,NaN,15.0,...,1021.1,23.0,4.1,167.1,14.4,7,NaN,2015-01-15T06:55:39,2015-01-15T17:30:03,0.0
15,2015-01-16,62.5,37.3,49.3,40.0,73.3,0,0.00,NaN,14.8,...,1021.1,27.1,3.6,151.2,13.1,7,NaN,2015-01-16T06:55:33,2015-01-16T17:30:51,0.0
16,2015-01-17,62.5,40.9,50.0,41.2,74.8,0,0.00,NaN,15.4,...,1020.0,29.2,3.8,170.2,14.7,6,NaN,2015-01-17T06:55:26,2015-01-17T17:31:40,0.0
17,2015-01-18,62.5,37.3,49.3,38.8,70.9,0,0.00,NaN,14.1,...,1019.8,25.2,4.1,193.5,16.7,7,NaN,2015-01-18T06:55:17,2015-01-18T17:32:28,0.0
18,2015-01-19,66.1,37.3,49.4,37.5,69.2,0,0.00,NaN,14.8,...,1019.9,25.1,4.2,192.9,16.7,7,NaN,2015-01-19T06:55:07,2015-01-19T17:33:17,0.0
19,2015-01-20,66.1,37.3,49.2,36.8,66.8,0,0.00,NaN,13.2,...,1022.5,33.3,4.1,181.8,15.7,7,NaN,2015-01-20T06:54:55,2015-01-20T17:34:06,0.0
20,2015-01-21,74.9,37.3,50.8,38.5,66.9,0,0.00,NaN,14.1,...,1024.5,25.1,4.0,193.7,16.6,7,NaN,2015-01-21T06:54:41,2015-01-21T17:34:55,0.0
21,2015-01-22,66.1,39.1,51.6,39.8,67.3,0,0.00,NaN,15.7,...,1022.8,69.7,3.8,187.8,16.1,7,NaN,2015-01-22T06:54:26,2015-01-22T17:35:44,0.0
22,2015-01-23,64.3,46.3,54.0,43.3,69.2,0,0.00,NaN,18.6,...,1020.0,71.8,4.2,186.9,15.9,7,NaN,2015-01-23T06:54:10,2015-01-23T17:36:33,0.0
23,2015-01-24,64.3,37.3,51.0,40.5,71.4,0,0.00,NaN,18.3,...,1020.1,44.7,3.9,194.5,16.8,7,NaN,2015-01-24T06:53:52,2015-01-24T17:37:22,0.0
24,2015-01-25,66.1,37.3,51.2,39.4,67.9,0,0.00,NaN,18.6,...,1021.2,61.3,4.3,189.6,16.3,7,NaN,2015-01-25T06:53:32,2015-01-25T17:38:11,0.0
25,2015-01-26,60.7,46.3,52.0,44.4,76.4,0,0.00,NaN,14.3,...,1021.9,88.9,3.0,94.0,8.3,4,NaN,2015-01-26T06:53:11,2015-01-26T17:39:00,0.0
26,2015-01-27,66.3,44.5,52.4,42.1,71.7,0,0.00,NaN,19.7,...,1020.2,55.0,3.7,123.3,10.5,5,NaN,2015-01-27T06:52:48,2015-01-27T17:39:49,0.0
27,2015-01-28,67.9,35.5,50.0,37.3,67.4,0,0.00,NaN,18.8,...,1017.7,25.4,3.7,206.6,17.8,8,NaN,2015-01-28T06:52:24,2015-01-28T17:40:38,0.0
28,2015-01-29,64.3,39.1,49.4,36.7,67.0,0,0.00,NaN,16.6,...,1018.8,51.8,3.9,176.5,15.4,7,NaN,2015-01-29T06:51:58,2015-01-29T17:41:26,0.0
29,2015-01-30,58.9,37.3,46.7,38.2,73.7,100,8.33,rain,18.6,...,1018.0,31.1,3.4,164.7,14.1,7,NaN,2015-01-30T06:51:31,2015-01-30T17:42:14,0.0
30,2015-01-31,62.5,35.5,46.9,36.4,70.9,0,0.00,NaN,15.7,...,1018.6,28.0,3.6,176.3,15.2,7,NaN,2015-01-31T06:51:03,2015-01-31T17:43:02,0.0
31,2015-02-01,60.7,37.3,47.7,38.8,73.9,0,0.00,NaN,16.1,...,1020.7,29.2,3.1,162.2,13.9,7,NaN,2015-02-01T06:50:33,2015-02-01T17:43:50,0.0
32,2015-02-02,66.1,37.3,50.0,39.0,69.4,0,0.00,NaN,16.6,...,1023.5,27.1,3.4,197.1,17.0,7,NaN,2015-02-02T06:50:02,2015-02-02T17:44:38,0.0
33,2015-02-03,69.7,39.1,53.2,40.4,67.2,0,0.00,NaN,30.0,...,1025.8,38.1,3.5,193.9,17.0,8,NaN,2015-02-03T06:49:29,2015-02-03T17:45:25,0.0
34,2015-02-04,75.5,42.7,54.9,41.4,65.4,100,4.17,rain,22.8,...,1021.9,30.6,4.4,213.5,18.6,8,NaN,2015-02-04T06:48:55,2015-02-04T17:46:12,1.0
35,2015-02-05,67.9,39.1,51.7,43.0,74.7,0,0.00,NaN,17.2,...,1020.3,27.4,4.0,199.3,17.2,7,NaN,2015-02-05T06:48:20,2015-02-05T17:46:59,0.0
36,2015-02-06,69.5,42.3,52.6,45.4,78.7,0,0.00,NaN,17.9,...,1019.5,52.0,3.4,158.1,13.5,7,NaN,2015-02-06T06:47:43,2015-02-06T17:47:45,0.0
37,2015-02-07,66.1,40.9,52.6,42.1,71.9,0,0.00,NaN,20.6,...,1019.3,41.5,3.9,204.0,17.7,8,NaN,2015-02-07T06:47:05,2015-02-07T17:48:31,0.0
38,2015-02-08,64.3,40.9,52.2,41.6,70.0,0,0.00,NaN,21.9,...,1020.3,65.9,3.9,157.3,13.6,7,NaN,2015-02-08T06:46:26,2015-02-08T17:49:16,0.0
39,2015-02-09,67.9,42.7,54.1,42.1,67.1,0,0.00,NaN,18.8,...,1021.1,30.2,4.0,203.3,17.6,8,NaN,2015-02-09T06:45:45,2015-02-09T17:50:02,0.0
40,2015-02-10,67.9,40.9,54.1,42.3,68.1,0,0.00,NaN,23.3,...,1020.8,24.8,4.1,219.7,19.0,8,NaN,2015-02-10T06:45:04,2015-02-10T17:50:47,0.0
41,2015-02-11,66.1,40.9,53.1,42.6,70.5,0,0.00,NaN,18.3,...,1019.4,48.3,3.3,198.7,17.1,8,NaN,2015-02-11T06:44:21,2015-02-11T17:51:31,0.0
42,2015-02-12,66.1,42.7,53.5,43.0,71.6,0,0.00,NaN,15.2,...,1017.3,57.0,3.4,162.0,14.0,7,NaN,2015-02-12T06:43:37,2015-02-12T17:52:15,0.0
43,2015-02-13,64.3,46.3,53.7,45.3,75.7,0,0.00,NaN,16.1,...,1015.1,55.4,3.3,152.4,13.0,6,NaN,2015-02-13T06:42:52,2015-02-13T17:52:59,0.0
44,2015-02-14,62.5,42.7,52.6,44.6,75.6,0,0.00,NaN,15.9,...,1015.0,51.7,2.8,132.3,11.5,5,NaN,2015-02-14T06:42:05,2015-02-14T17:53:42,0.0
45,2015-02-15,62.5,48.1,54.0,45.4,74.2,0,0.00,NaN,14.5,...,1017.0,76.9,2.6,108.8,9.3,5,NaN,2015-02-15T06:41:18,2015-02-15T17:54:25,0.0
46,2015-02-16,66.1,48.1,55.0,45.2,71.2,0,0.00,NaN,16.3,...,1020.2,53.3,2.5,186.0,16.0,7,NaN,2015-02-16T06:40:30,2015-02-16T17:55:08,0.0
47,2015-02-17,67.9,46.3,55.9,45.6,71.2,0,0.00,NaN,13.6,...,1018.1,42.8,3.0,155.3,13.5,6,NaN,2015-02-17T06:39:40,2015-02-17T17:55:50,0.0
48,2015-02-18,67.9,46.3,55.5,45.6,71.6,0,0.00,NaN,13.2,...,1017.1,61.1,2.9,139.8,12.0,6,NaN,2015-02-18T06:38:50,2015-02-18T17:56:31,0.0
49,2015-02-19,79.1,44.5,55.3,45.5,72.0,100,4.17,rain,17.4,...,1018.6,39.6,4.4,177.7,15.2,7,NaN,2015-02-19T06:37:58,2015-02-19T17:57:13,10.9

In [33]:
data?

Type:        DataFrame
String form:
datetime  tempmax  tempmin  temp   dew  humidity  precipprob  \
           0     2015-01-01     60.7 <...> 9.9898
           3467  2025-06-30T05:11:09  2025-06-30T19:03:21       13.0048

           [3468 rows x 22 columns]
Length:      3468
File:        ~/miniconda3/lib/python3.13/site-packages/pandas/__init__.py
Docstring:
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
    If ``data`` is DataFrame then is ignored.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {"col1": [1, 2], "col2": [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {"col1": [0, 1, 2, 3], "col2": pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(
...     np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=["a", "b", "c"]
... )
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array(
...     [(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...     dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")],
... )
>>> df3 = pd.DataFrame(data, columns=["c", "a"])
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3

In [34]:
data.dtypes

datetime                str
tempmax             float64
tempmin             float64
temp                float64
dew                 float64
humidity            float64
precipprob            int64
precipcover         float64
preciptype              str
windgust            float64
windspeed           float64
winddir             float64
sealevelpressure    float64
cloudcover          float64
visibility          float64
solarradiation      float64
solarenergy         float64
uvindex               int64
severerisk          float64
sunrise                 str
sunset                  str
precipitation       float64
dtype: object

In [35]:
columns_to_keep = ['datetime', 'humidity','precipitation','tempmax','tempmin','temp', 'cloudcover','solarenergy']

new_df = data[columns_to_keep]

new_df[:10]

,datetime,humidity,precipitation,tempmax,tempmin,temp,cloudcover,solarenergy
0,2015-01-01,74.7,0.8,60.7,39.1,50.0,79.1,8.3
1,2015-01-02,80.1,0.0,71.0,49.9,54.9,93.3,3.3
2,2015-01-03,86.3,0.5,67.7,48.1,54.8,90.3,5.0
3,2015-01-04,85.5,0.5,69.9,48.1,54.5,67.1,10.3
4,2015-01-05,83.2,0.0,64.3,42.7,51.3,41.6,12.0
5,2015-01-06,78.0,0.0,62.5,46.3,52.2,62.5,8.5
6,2015-01-07,77.8,0.0,60.7,43.4,50.3,65.7,8.9
7,2015-01-08,76.4,0.0,71.7,39.1,49.3,50.1,9.7
8,2015-01-09,72.8,0.0,64.3,39.1,48.4,24.0,14.8
9,2015-01-10,68.2,0.0,67.9,35.5,47.9,22.9,16.2

In [36]:
new_df.dtypes

datetime             str
humidity         float64
precipitation    float64
tempmax          float64
tempmin          float64
temp             float64
cloudcover       float64
solarenergy      float64
dtype: object

In [37]:
new_df['datetime'] = pd.to_datetime(new_df['datetime'])

new_df = new_df.set_index('datetime')

In [38]:
new_df[0:10]

,humidity,precipitation,tempmax,tempmin,temp,cloudcover,solarenergy
datetime,,,,,,,
2015-01-01,74.7,0.8,60.7,39.1,50.0,79.1,8.3
2015-01-02,80.1,0.0,71.0,49.9,54.9,93.3,3.3
2015-01-03,86.3,0.5,67.7,48.1,54.8,90.3,5.0
2015-01-04,85.5,0.5,69.9,48.1,54.5,67.1,10.3
2015-01-05,83.2,0.0,64.3,42.7,51.3,41.6,12.0
2015-01-06,78.0,0.0,62.5,46.3,52.2,62.5,8.5
2015-01-07,77.8,0.0,60.7,43.4,50.3,65.7,8.9
2015-01-08,76.4,0.0,71.7,39.1,49.3,50.1,9.7
2015-01-09,72.8,0.0,64.3,39.1,48.4,24.0,14.8
2015-01-10,68.2,0.0,67.9,35.5,47.9,22.9,16.2

In [43]:
expected_dates = pd.date_range(start=new_df.index.min(), end=new_df.index.max())
missing_dates = expected_dates.difference(new_df.index)
missing_dates

DatetimeIndex(['2015-07-01', '2015-07-02', '2015-07-03', '2015-07-04',
               '2015-07-05', '2015-07-06', '2015-07-07', '2015-07-08',
               '2015-07-09', '2015-07-10',
               ...
               '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
               '2016-06-25', '2016-06-26', '2016-06-27', '2016-06-28',
               '2016-06-29', '2016-06-30'],
              dtype='datetime64[us]', length=366, freq='D')

In [39]:
new_df.isnull().sum()

humidity         0
precipitation    0
tempmax          0
tempmin          0
temp             0
cloudcover       0
solarenergy      0
dtype: int64

In [ ]:
#THings to do 

1) Check for missing missing_dates
2) Poprpose XGBoost